version: '3'

services:
  # service1:
  #   image: nc-server  
  #   environment: 
  #     - ENV_VAR=service 1
  #   ports:
  #     - 91:8080
  #   # networks:
  #     # - test_external_net

  service1:
    image: py-server
    environment: 
      - CUSTOM_RESPONSE=service 1
    ports:
      - 91:8080
    # networks:
      # - test_external_net

  # service2:
  #   image: nc-server
  #   environment: 
  #     - ENV_VAR=service 2
  #   networks:
  #     - test_external_net_1
  #   ports:
  #     - 92:8080

  # service3:
  #   image: nc-server
  #   environment: 
  #     - ENV_VAR=service 3  
  #   networks:
  #     - test_external_net_1
  #   ports:
  #     - 93:8080

  unique_service:
    image: nc-server  
    environment: 
      - ENV_VAR=unique_service
    ports:
      - 94:8080
    # networks:
      # - test_external_net

  router:
    image: nginx
    depends_on:
      - service1
      # - service2
      # - service3
      - unique_service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;' 
    # networks:
      # - test_external_net
    ports:
      - 85:80
  
# networks:
  # test_external_net:
    # external: true
    # driver: bridge
